### ISSUE TITLE
无法导入tmx文件

### ISSUE THREAD

**Issue by Panaxnotoginseng** [BLKSerene/Wordless#37]
我导入双语txm文件后出现如下报错：
Traceback (most recent call last):
  File "wordless\wl_file_area.py", line 1019, in run
  File "wordless\wl_utils\wl_conversion.py", line 59, in to_iso_639_3
Exception: Failed to convert ISO 639-1 code "es_es" to ISO 639-3 code!

版本是3.5，Windows系统，请问这是我的文件有问题吗？

**Comment by BLKSerene** [comment]
感谢反馈 bug 已记录 西班牙语带地区代码的 例如 es_es 没有正确处理 下个版本会修复
现在暂时可以用记事本等文本工具打开TMX文件 搜索应该有这一行：

`<tuv xml:lang="es-ES">`

 把里面的 es-ES 改成 es 即可：

`<tuv xml:lang="es">`
