### ISSUE TITLE
无法下载模型

### ISSUE THREAD

**Issue by Panaxnotoginseng** [BLKSerene/Wordless#38]
下载模型时出现如下报错：
Traceback (most recent call last):
  File "wordless\wl_nlp\wl_nlp_utils.py", line 330, in run
  File "stanza\resources\common.py", line 606, in download
  File "stanza\resources\common.py", line 535, in download_models
  File "stanza\resources\common.py", line 154, in request_file
  File "stanza\resources\common.py", line 107, in assert_file_exists
ValueError: md5 for D:\Program Files (x86)\wordless_3.5.0_windows\Wordless\libs\stanza_resources\es\tokenize\ancora.pt is 808f27248700ae3e52014e7ba3f9c3aa, expected c053221c33efc6435e60959206942830

我没有使用任何代理，但我ip在西班牙。
<img width="311" alt="1730975612725" src="https://github.com/user-attachments/assets/9fe7414b-9c5a-4be8-a267-05f5ea8d21d3">

**Comment by BLKSerene** [comment]
[resources.json](https://github.com/user-attachments/files/17660264/resources.json)
你好 请下载这个文件后复制到 Wordless/libs/stanza/resources下后覆盖掉同名的文件
Stanza的模型资源文件目前版本不会自动更新 这个bug别人已经反馈过了 下个版本也会修复

**Comment by Panaxnotoginseng** [comment]
谢谢！

**Comment by Mosw5871** [comment]
> [resources.json](https://github.com/user-attachments/files/17660264/resources.json) 你好 请下载这个文件后复制到 Wordless/libs/stanza/resources下后覆盖掉同名的文件（仅适用于 3.5.0） Stanza的模型资源文件目前版本不会自动更新 这个bug别人已经反馈过了 下个版本也会修复

你好，请问字啊 Mac 中我找不到Wordless/libs/stanza/resources路径，能请问一下这个应该怎么打开吗？谢谢

**Comment by Mosw5871** [comment]
感谢您的回复！谢谢！

----- 原始邮件 -----
发件人: "BLKSerene" ***@***.***>
收件人: "BLKSerene/Wordless" ***@***.***>
抄送: "Wei Shi" ***@***.***>, "Mention" ***@***.***>
发送时间: 星期日, 2024年 12 月 01日 下午 4:04:24
主题: Re: [BLKSerene/Wordless] 无法下载模型 (Issue #38)

@Mosw5871 mac 系统可以参考 README - Download 下面 Note 3 里的路径或 README - Need Help? 里的 b 站视频教程：https://www.bilibili.com/video/BV1DF4m1N7hz/?spm_id_from=333.999.0.0

右键 Wordless.app 选择 `Show Package Contents` 然后定位到 `Contents/Frameworks/stanza_resources` 目录下 也是覆盖掉同名的文件
