### ISSUE TITLE
无法下载模型

### ISSUE THREAD

**Issue by Dborgia** [BLKSerene/Wordless#40]
叶博士您好，

     下载模型时报错
Traceback (most recent call last):
  File "urllib3\response.py", line 748, in _error_catcher
  File "urllib3\response.py", line 894, in _raw_read
urllib3.exceptions.IncompleteRead: IncompleteRead(4826083 bytes read, 33245942 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\models.py", line 820, in generate
  File "urllib3\response.py", line 1060, in stream
  File "urllib3\response.py", line 977, in read
  File "urllib3\response.py", line 872, in _raw_read
  File "contextlib.py", line 158, in __exit__
  File "urllib3\response.py", line 772, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(4826083 bytes read, 33245942 more expected)', IncompleteRead(4826083 bytes read, 33245942 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wordless\wl_nlp\wl_nlp_utils.py", line 330, in run
  File "stanza\resources\common.py", line 606, in download
  File "stanza\resources\common.py", line 535, in download_models
  File "stanza\resources\common.py", line 152, in request_file
  File "stanza\resources\common.py", line 121, in download_file
  File "requests\models.py", line 822, in generate
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(4826083 bytes read, 33245942 more expected)', IncompleteRead(4826083 bytes read, 33245942 more expected))

  我试了一下38号提问的办法，替换了json文件，但还是没有解决， 版本是3.5

**Comment by BLKSerene** [comment]
请参考 README 下载部分下的备注3：https://github.com/BLKSerene/Wordless/blob/main/doc/trs/zho_cn/README.md#%E4%B8%8B%E8%BD%BD
或者 README 里 Need Help? 这部分里的视频教程：https://www.bilibili.com/video/BV1DF4m1N7hz/
